sylius_grid:
    grids:
        app_shop_product_search:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.product.class%"
                    repository:
                        method: createSearchShopListQueryBuilder
                        arguments:
                            channel: "expr:service('sylius.context.channel').getChannel()"
                            locale: "expr:service('sylius.context.locale').getLocaleCode()"
                            criteria: "expr:service('request_stack').getCurrentRequest().query.all('criteria')"
            limits: [ 9, 18, 27 ]
            fields:
                createdAt:
                    type: datetime
                    sortable: ~
                position:
                    type: string
                    sortable: productTaxon.position
                name:
                    type: string
                    sortable: translation.name
                price:
                    type: int
                    sortable: channelPricing.price
            filters:
                search_value:
                    type: array_search
                    label: sylius.ui.search
                    options:
                        fields: [ translation.slug, translation.name, variant.code, code ]
                    form_options:
                        attr:
                            class: 'array-search'
                    template: '@SyliusShop/Search/Filter/search_value.html.twig'
